# Generated by Django 4.1 on 2022-08-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multilogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthtoken',
            options={'verbose_name': 'OAuth Token', 'verbose_name_plural': 'OAuth Tokens'},
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='access_token',
            field=models.TextField(default=None, null=True),
        ),
    ]
